### ISSUE TITLE
Allow comparing to specific commits rather than a branch

### ISSUE THREAD

**Issue by kboom** [sajalverma17/GitBranchDiffer#38]
Many times, I find myself wanting to compare to the commit I branched from rather than to master.
It would be useful to allow using individual commits (SHA) rather than branch names as a base.

Magnificent work here!

**Comment by sajalverma17** [comment]
I've merged the feature to master now. You can give it a test if you want by downloading the artifacts from this [CI build](https://github.com/sajalverma17/GitBranchDiffer/actions/runs/3837615183) (version 1.1.0.65). Running `GitBranchDiffer.vsix` will install that version of Git Branch Differ to your VS2022. 

I'll update Github Action workflows and some related code and release soon.

**Comment by sajalverma17** [comment]
This has been released in v1.1.0
